### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by kklooster3910** [kklooster3910/500kicks#2]
* [ ] - Users can sign up, sign in, logout
* [ ] - Users can use a demo login to try the site
* [ ] - Users can't use certain features when logged, ie: not visiting sign up/login page
* [ ] - Adequate styling / ease of use

**Comment by wongshington** [comment]
the above check boxes are good, it won't let me check em off right now though
- [ ]  can you add a demo login button to the session forms as well. 
- [ ]  I can still see a user's profile page even when i'm logged out

**Comment by wongshington** [comment]
- [ ] probs don't need the alert after your demo login

**Comment by kklooster3910** [comment]
aye, fixed
